# Generated by Django 4.0.3 on 2022-04-01 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookinstance_borrewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='borrewer',
            new_name='borrower',
        ),
    ]
